### ISSUE TITLE
Matlab code uses UTM and not GPS

### ISSUE THREAD

**Issue by drdms2020** [alirezaahmadi/KalmanFilter-Vehicle-GNSS-INS#1]
Hi,
The measurement function that is used to update the filter uses UTM and not the GPS. The tutorial talks about using GPS and IMU sensor for prediction. Can you clarify this? Should UTM be subst with gps?
  z_k = [UTM(cnt,1);
         UTM(cnt,2);
         -imu.acc_ib_b(cnt_b,1);
         imu.omg_ib_b(cnt_b,3)]; 

Thanks
DMS

**Comment by alirezaahmadi** [comment]
you are right, GPS has been used as a general name !!
